export const USER_ACTIONS = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  SET_LOGGED_IN_STATUS: 'SET_LOGGED_IN_STATUS'
}

export const PRODUCT_ACTIONS = {
  SET_PRODUCTS: 'SET_PRODUCTS',
  SET_PRODUCT: 'SET_PRODUCT'
}